name: Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: public_html/heisenbergstudios/
          exclude: |
            **/.git*
            **/.git*/**
            **/.env*
            **/.npmrc
            **/.yarnrc
            **/.aws/**
            **/.docker/**
            **/.kube/**
            **/.config/**
            **/.vercel/**
            **/node_modules/**
            **/.github/**
            **/schema*.sql
            **/make_hash.php